# permissions for end users to view seaweeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seaweedfs-operator.fullname" . }}-viewer
rules:
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - seaweeds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seaweed.seaweedfs.com
  resources:
  - seaweeds/status
  verbs:
  - get
