---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
data:
  CSI_ENABLE_CSIADDONS: "true"
  CSI_PLUGIN_TOLERATIONS: |2-
    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoExecute
  CSI_PROVISIONER_TOLERATIONS: |2-
    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Exists
      effect: NoExecute
