apiVersion: v2
name: seaweedfs-operator
description: Master chart to deploy SeaweedFS Operator
version: 1.0.0
home: >-
  https://github.com/lightning-it/helm-charts/tree/main/charts/seaweedfs-operator
dependencies:
  - name: seaweedfs-operator
    version: 0.1.36
    repository: https://seaweedfs.github.io/seaweedfs-operator/

