---
# Using sub-chart helper-operator
helper-operator:
  operators:
     cert-manager-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: cert-manager-operator
        create: true
      subscription:
        channel: stable-v1
        approval: Manual
        operatorName: openshift-cert-manager-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        csv: cert-manager-operator.v1.18.1
      operatorgroup:
        create: true
        notownnamespace: false

# Using sub-chart helper-status-checker
helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: cert-manager-operator
      installCSV: cert-manager-operator.v1.18.1
      namespace:
        name: cert-manager-operator
      serviceAccount:
        name: "sa-cert-manager-operator"
