---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: lso-volumeset
  namespace: {{ .Values.namespace.name }}
spec:
  nodeSelector:
    nodeSelectorTerms:
{{ toYaml .Values.nodeSelectorTerms | indent 6 }}
  tolerations:
{{ toYaml .Values.tolerations | indent 4 }}
  deviceInclusionSpec:
    deviceTypes:
      - disk
    minSize: 1Gi
  storageClassName: lso-volumeset
  volumeMode: Block
