---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Values.issuer.hashicorpVault.caBundleSecretRef.name }}
  namespace: {{ .Values.vaultAppRoleSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.issuer.hashicorpVault.caBundleSecretRef.syncwave | quote }}
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
data:
  ca.crt: |
{{ .Values.issuer.hashicorpVault.caBundleSecretRef.value | indent 4}}
{{- if .Values.css_enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.vaultAppRoleSecret.name }}
  namespace: {{ .Values.vaultAppRoleSecret.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.css_name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.vaultAppRoleSecret.name }}
    template:
      engineVersion: v2
      data:
        secretId: >-
          {{ printf "{{ .secret_id }}" }}
  data:
    - secretKey: secret_id
      remoteRef:
        key: {{ .Values.css_secret_path }}
        property: secret_id
{{- else }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Values.vaultAppRoleSecret.name }}
  namespace: {{ .Values.vaultAppRoleSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.vaultAppRoleSecret.syncwave | quote }}
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
stringData:
  secretId: {{ .Values.vaultAppRoleSecret.secret }}
{{- end }}
