{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-db
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.externalSecrets.cluster_secret_store }}
    kind: ClusterSecretStore
  target:
    name: guacamole-db
    template:
      engineVersion: v2
      data:
        rdsUsername: >-
          {{ `{{ .rdsUsername }}` }}
        user-password: >-
          {{ `{{ index . "user-password" }}` }}
        postgres-password: >-
          {{ `{{ index . "postgres-password" }}` }}
  data:
    - secretKey: rdsUsername
      remoteRef:
        key: {{ include "guacamole.SecretKey" . | trim }}
        property: rdsUsername
    - secretKey: user-password
      remoteRef:
        key: {{ include "guacamole.SecretKey" . | trim }}
        property: user-password
    - secretKey: postgres-password
      remoteRef:
        key: {{ include "guacamole.SecretKey" . | trim }}
        property: postgres-password
{{- end }}
