{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-db
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.externalSecrets.cluster_secret_store }}
    kind: ClusterSecretStore
  target:
    name: guacamole-db
    template:
      engineVersion: v2
      data:
        rdsUsername: >-
          {{ printf "{{ .rdsUsername }}" }}
        rdsPassword: >-
          {{ printf "{{ .rdsPassword }}" }}
  data:
    - secretKey: rdsUsername
      remoteRef:
        key: {{ include "guacamole.SecretKey" . | trim }}
        property: rdsUsername
    - secretKey: rdsPassword
      remoteRef:
        key: {{ include "guacamole.SecretKey" . | trim }}
        property: rdsPassword
{{- end }}
