apiVersion: v2
name: seaweedfs
description: Master chart to deploy SeaweedFS
version: 1.0.0
home: >-
  https://github.com/lightning-it/helm-charts/tree/main/charts/seaweedfs
dependencies:
  - name: seaweedfs
    version: 4.33.0
    repository: https://seaweedfs.github.io/seaweedfs/helm

