{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.name }}-user
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster.name }}-user
    template:
      engineVersion: v2
      data:
        username: >-
          {{ printf "{{ .rds_username }}" }}
        password: >-
          {{ printf "{{ .rds_password }}" }}
  data:
    - secretKey: rds_username
      remoteRef:
        key: {{ include "cloudnative-pg-instance.SecretKey" . | trim }}
        property: rds_username
    - secretKey: rds_password
      remoteRef:
        key: {{ include "cloudnative-pg-instance.SecretKey" . | trim }}
        property: rds_password
{{- if and .Values.backup.enabled (or .Values.backup.s3Backup.enabled .Values.backup.s3Recovery.enabled) (or (not .Values.backup.s3Backup.createBucket) .Values.backup.s3Backup.endpointCa)  }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.name }}-s3-backup
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster.name }}-s3-backup
    template:
      engineVersion: v2
      data:
{{- if not .Values.backup.s3Backup.createBucket }}
        ACCESS_KEY_ID: >-
          {{ printf "{{ .s3_backup_access_key_id }}" }}
        ACCESS_SECRET_KEY: >-
          {{ printf "{{ .s3_backup_access_secret_id }}" }}
{{- end }}
{{- if .Values.backup.s3Backup.endpointCa }}
        ca.crt: >-
          {{ printf "{{ .s3_backup_endpoint_ca }}" }}
{{- end }}
  data:
{{- if not .Values.backup.s3Backup.createBucket }}
    - secretKey: s3_backup_access_key_id
      remoteRef:
        key: {{ include "cloudnative-pg-instance.SecretKey" . | trim }}
        property: s3_backup_access_key_id
    - secretKey: s3_backup_access_secret_id
      remoteRef:
        key: {{ include "cloudnative-pg-instance.SecretKey" . | trim }}
        property: s3_backup_access_secret_id
{{- end }}
{{- if .Values.backup.s3Backup.endpointCa }}
    - secretKey: s3_backup_endpoint_ca
      remoteRef:
        key: {{ .Values.externalSecrets.rootCaSecretPath | default (include "cloudnative-pg-instance.SecretKey" .) | trim }}
        property: root_ca
{{- end }}
{{- if .Values.backup.s3Recovery.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.name }}-s3-recovery
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster.name }}-s3-recovery
    template:
      engineVersion: v2
      data:
{{- if not .Values.backup.s3Backup.createBucket }}
        ACCESS_KEY_ID: >-
          {{ printf "{{ .s3_recovery_access_key_id }}" }}
        ACCESS_SECRET_KEY: >-
          {{ printf "{{ .s3_recovery_access_secret_id }}" }}
{{- end }}
{{- if .Values.backup.s3Recovery.endpointCa }}
        ca.crt: >-
          {{ printf "{{ .s3_recovery_endpoint_ca }}" }}
{{- end }}
  data:
{{- if not .Values.backup.s3Backup.createBucket }}
    - secretKey: s3_recovery_access_key_id
      remoteRef:
        key: {{ include "cloudnative-pg-instance.SecretKey" . | trim }}
        property: s3_recovery_access_key_id
    - secretKey: s3_recovery_access_secret_id
      remoteRef:
        key: {{ include "cloudnative-pg-instance.SecretKey" . | trim }}
        property: s3_recovery_access_secret_id
{{- end }}
{{- if .Values.backup.s3Backup.endpointCa }}
    - secretKey: s3_recovery_endpoint_ca
      remoteRef:
        key: {{ .Values.externalSecrets.rootCaSecretPath | default (include "cloudnative-pg-instance.SecretKey" .) | trim }}
        property: root_ca
{{- end }}
{{- end }}
{{- end }}
{{- else }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.cluster.name }}-user
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.cluster.username }}
  password: {{ default (randAlphaNum 16 ) .Values.password }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.cluster.name }}-s3-backup
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt:
    {{ .Values.backup.s3Backup.endpointCaCertificate | toYaml | indent 2 }}
type: kubernetes.io/tls
{{- end }}
