{{- range .Values.s3credentials }}
{{- if .enabled }}
---
apiVersion: seaweed.seaweedfs.com/v1
kind: S3Credentials
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "seaweedfs-instance.labels" $ | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- end }}
