{{- include "openshift-ingressoperatorpatch.validateCertificateSource" . -}}
{{- if eq .Values.certificateSource "external-secrets" }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.default_ingress_certificate_secret }}
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.default_ingress_certificate_secret }}
    template:
      type: kubernetes.io/tls
  data:
{{ include "eso.dataEntries" .Values.externalSecrets.ingress.data | indent 4 }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.default_api_certificate_secret }}
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.default_api_certificate_secret }}
    template:
      type: kubernetes.io/tls
  data:
{{ include "eso.dataEntries" .Values.externalSecrets.api.data | indent 4 }}
{{- end }}
