---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  routeAdmission:
    wildcardPolicy: {{- if .Values.allowWildcards }} WildcardsAllowed {{- else }} WildcardsDisallowed {{- end }}
{{- if .Values.ingress.enabled }}
  defaultCertificate:
    name: {{ .Values.ingress.certificateSecret }}
{{- end }}
